export const artistSeeds = [
  {
    name: "Riverline",
    bio: "Glassy ambient layers with slow-blooming crescendos.",
    genres: ["ambient", "chill"],
    heroImage: "/assets/img/cover-1.svg",
    monthlyListeners: 128400,
  },
  {
    name: "Hollow North",
    bio: "Indie textures stitched with soft analog warmth.",
    genres: ["indie", "alt"],
    heroImage: "/assets/img/cover-2.svg",
    monthlyListeners: 98320,
  },
  {
    name: "Solar Drift",
    bio: "Polished synth lines and deep pulse rhythms.",
    genres: ["electronic", "synth"],
    heroImage: "/assets/img/cover-3.svg",
    monthlyListeners: 210900,
  },
  {
    name: "Juniper Lane",
    bio: "Dusty folk arrangements and intimate vocals.",
    genres: ["folk", "acoustic"],
    heroImage: "/assets/img/cover-4.svg",
    monthlyListeners: 66410,
  },
  {
    name: "Night Atlas",
    bio: "Cinematic post-rock with long-form movement.",
    genres: ["post-rock", "cinematic"],
    heroImage: "/assets/img/cover-5.svg",
    monthlyListeners: 142770,
  },
];

export const albumSeeds = [
  {
    title: "Glass Horizons",
    artistIndex: 0,
    coverUrl: "/assets/img/cover-1.svg",
    year: 2024,
    description: "Wide open ambient space with tides of light.",
  },
  {
    title: "Northern Bloom",
    artistIndex: 1,
    coverUrl: "/assets/img/cover-2.svg",
    year: 2023,
    description: "Warm indie tones that feel like golden hour.",
  },
  {
    title: "Signal Lanterns",
    artistIndex: 2,
    coverUrl: "/assets/img/cover-3.svg",
    year: 2024,
    description: "Neon synth pulses and midnight momentum.",
  },
  {
    title: "Juniper Tides",
    artistIndex: 3,
    coverUrl: "/assets/img/cover-4.svg",
    year: 2022,
    description: "Acoustic drift with a calm, coastal breeze.",
  },
  {
    title: "Atlas in Motion",
    artistIndex: 4,
    coverUrl: "/assets/img/cover-5.svg",
    year: 2023,
    description: "Cinematic builds and long-form movement.",
  },
];

export const trackSeeds = [
  {
    title: "Nightwater",
    artistIndex: 0,
    albumIndex: 0,
    durationSec: 228,
    coverUrl: "/assets/img/cover-1.svg",
    popularity: 78,
  },
  {
    title: "Quiet Halo",
    artistIndex: 0,
    albumIndex: 0,
    durationSec: 206,
    coverUrl: "/assets/img/cover-1.svg",
    popularity: 64,
  },
  {
    title: "Low Orbit",
    artistIndex: 0,
    albumIndex: 0,
    durationSec: 242,
    coverUrl: "/assets/img/cover-1.svg",
    popularity: 71,
  },
  {
    title: "Cedar Lines",
    artistIndex: 1,
    albumIndex: 1,
    durationSec: 214,
    coverUrl: "/assets/img/cover-2.svg",
    popularity: 66,
  },
  {
    title: "Soft Parade",
    artistIndex: 1,
    albumIndex: 1,
    durationSec: 198,
    coverUrl: "/assets/img/cover-2.svg",
    popularity: 72,
  },
  {
    title: "Ash and Amber",
    artistIndex: 1,
    albumIndex: 1,
    durationSec: 232,
    coverUrl: "/assets/img/cover-2.svg",
    popularity: 63,
  },
  {
    title: "Signal Glow",
    artistIndex: 2,
    albumIndex: 2,
    durationSec: 204,
    coverUrl: "/assets/img/cover-3.svg",
    popularity: 81,
  },
  {
    title: "Midnight Circuit",
    artistIndex: 2,
    albumIndex: 2,
    durationSec: 238,
    coverUrl: "/assets/img/cover-3.svg",
    popularity: 76,
  },
  {
    title: "Solar Run",
    artistIndex: 2,
    albumIndex: 2,
    durationSec: 219,
    coverUrl: "/assets/img/cover-3.svg",
    popularity: 70,
  },
  {
    title: "Golden Thread",
    artistIndex: 3,
    albumIndex: 3,
    durationSec: 188,
    coverUrl: "/assets/img/cover-4.svg",
    popularity: 61,
  },
  {
    title: "Harborlight",
    artistIndex: 3,
    albumIndex: 3,
    durationSec: 207,
    coverUrl: "/assets/img/cover-4.svg",
    popularity: 58,
  },
  {
    title: "Juniper Rain",
    artistIndex: 3,
    albumIndex: 3,
    durationSec: 226,
    coverUrl: "/assets/img/cover-4.svg",
    popularity: 69,
  },
  {
    title: "Gravity Lines",
    artistIndex: 4,
    albumIndex: 4,
    durationSec: 251,
    coverUrl: "/assets/img/cover-5.svg",
    popularity: 75,
  },
  {
    title: "Glass Cities",
    artistIndex: 4,
    albumIndex: 4,
    durationSec: 263,
    coverUrl: "/assets/img/cover-5.svg",
    popularity: 68,
  },
  {
    title: "Atlas Bloom",
    artistIndex: 4,
    albumIndex: 4,
    durationSec: 239,
    coverUrl: "/assets/img/cover-5.svg",
    popularity: 73,
  },
];

export const playlistSeeds = [
  {
    name: "Evening Flow",
    description: "Slow, smooth pacing for late sessions.",
    coverUrl: "/assets/img/cover-6.svg",
    trackIndexes: [0, 1, 2, 3, 4],
  },
  {
    name: "City Focus",
    description: "Polished electronics to keep momentum steady.",
    coverUrl: "/assets/img/cover-3.svg",
    trackIndexes: [5, 6, 7, 8, 9],
  },
  {
    name: "Golden Hour",
    description: "Warm acoustic tones with soft synth shimmer.",
    coverUrl: "/assets/img/cover-4.svg",
    trackIndexes: [10, 11, 12, 13, 14],
  },
];
